# Configuration for the MCP client application
server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp  # Application name
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}  # API key for DashScope AI service
    mcp.client:
      toolcallback.enabled: true  # Enable MCP tool callbacks
      sse.connections:
        gateway-server:
          url: http://localhost:8081  # URL of the MCP Gateway server
  mandatory-file-encoding: UTF-8

